### PR TITLE
Enhanced debug prints and image test vectors

### PR DESCRIPTION
**Pull request by nkapu**
Proposal to unify and enhance partition and image loading related debug prints. Also includes format string vs. parameter type mismatch fixes and proposal to use CRLF in debug prints for serial console friendliness.

Includes a script to generate image test vectors to exercise out different partition and image construction mistakes. Corresponding debug print output is given below:

```
$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-01-no-boot-partition.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part -1
wolfBoot_start(): no partitions found
boot_panic(): entered - to die here

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-02-oversized-boot-image-with-signed-dtb.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_open_image(): image size 0x01400000 exceeds max available partition space 0x00f5fc00
wolfBoot_start(): Failure -1: Part 0, Hdr ?, Hash ?, Sig ?
wolfBoot_start(): no fallback image available
boot_panic(): entered - to die here

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-03-tampered-boot-image-with-signed-dtb.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_start(): Failure 1: Part 0, Hdr ok, Hash ?, Sig ?
wolfBoot_start(): no fallback image available
boot_panic(): entered - to die here

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-04-forged-boot-image-with-signed-dtb.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_start(): Failure -1: Part 0, Hdr ok, Hash ok, Sig ?
wolfBoot_start(): no fallback image available
boot_panic(): entered - to die here

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-05-no-dtb-partition.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_start(): Firmware Valid
wolfBoot_open_image(): looking for DTB boot partition at 0x00000000000A0000
wolfBoot_open_image(): value 0xffffffff at 0x00000000000A0000 does not match expected DTB image magic 0xedfe0dd0
wolfBoot_start(): Booting at 0x0000000003000000, with DTB at 0x0000000000000000

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-06-with-tampered-dtb.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_start(): Firmware Valid
wolfBoot_open_image(): looking for DTB boot partition at 0x00000000000A0000
wolfBoot_open_image(): value 0x464c4f57 at 0x00000000000A0000 does not match expected DTB image magic 0xedfe0dd0
wolfBoot_start(): Booting at 0x0000000003000000, with DTB at 0x0000000000000000

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-07-with-signed-dtb.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_start(): Firmware Valid
wolfBoot_open_image(): looking for DTB boot partition at 0x00000000000A0000
wolfBoot_open_image(): value 0x464c4f57 at 0x00000000000A0000 does not match expected DTB image magic 0xedfe0dd0
wolfBoot_start(): Booting at 0x0000000003000000, with DTB at 0x0000000000000000

$ qemu-system-aarch64 -M raspi3 -serial null -serial stdio -kernel image-test-vectors/test-08-with-raw-dtb.img

raspi3:debug_uart_init() completed
raspi3:hal_init() completed
wolfBoot_start(): entered
wolfBoot_start(): Active Part 0
wolfBoot_open_image(): looking for boot partition at 0x00000000000C0000
wolfBoot_start(): Firmware Valid
wolfBoot_open_image(): looking for DTB boot partition at 0x00000000000A0000
wolfBoot_start(): Booting at 0x0000000003000000, with DTB at 0x0000000004000000
```

### CODE REVIEW

**Comment by dgarske** [comment]
Hi @nkapu , I like these changes. We first need to have a contributor agreement on file for you.

**Comment by iolivergithub** [comment]
Contributor agreement in progress

**Comment by dgarske** [comment]
@nkapu , can you resolve the conflicts in this PR? Thanks, David Garske, wolfSSL

**Comment by dgarske** [comment]
Moved to https://github.com/nokia/wolfBoot/pull/1

**Pull request closed without merging**
