### PR TITLE
Encryption bug - integrity check of boot partition fails after updating

### PR DESCRIPTION
**Pull request by LOorts-Aloxy**
This bug got introduced in https://github.com/wolfSSL/wolfBoot/commit/72eb2c205ba49df5ad50365712d9b2e67452bd38.

### CODE REVIEW

**Comment by danielinux** [comment]
Thanks for spotting this.
Since each sector uses 4 bits (one nibble) to keep its state, I believe that the formula to calculate the overhead should be:
`(4 + 1 + (WOLFBOOT_PARTITION_SIZE  / (2 * WOLFBOOT_SECTOR_SIZE))) /* MAGIC + PART_FLAG (1B) + (N_SECTORS / 2)`

**Comment by LOorts-Aloxy** [comment]
Tested on our board with the proposed OVERHEAD and seems to work!

**Comment by danielinux** [comment]
Thanks! Could you please fix the comment as well `(N_SECTORS / 2)`? I will merge right away and re-run all the tests.

**Comment by LOorts-Aloxy** [comment]
should be fixed btw

**Comment by danielinux** [comment]
Merged, thanks!

**Pull request merged**
