### PR TITLE
wolfBoot cmake support.

### PR DESCRIPTION
**Pull request by lealem47**

### CODE REVIEW

**Review by danielinux — CHANGES_REQUESTED** [review]
A few things I would like to improve, before going ahead with this.

- running cmake with default parameters leads to a segmentation fault.
 e.g. with the command line 
 ```
 -DWOLFBOOT_TARGET=stm32f4 -DWOLFBOOT_PARTITION_SIZE=0x20000 -DWOLFBOOT_SECTOR_SIZE=0x20000 -DWOLFBOOT_PARTITION_BOOT_ADDRESS=0x08020000 -DWOLFBOOT_PARTITION_UPDATE_ADDRESS=0x08040000 -DWOLFBOOT_PARTITION_SWAP_ADDRESS=0x08060000
 ```
I got:
```
 [ 26%] Generating keystore.c and signing private key
make[2]: *** [CMakeFiles/keystore.dir/build.make:79: keystore.c] Segmentation fault (core dumped)
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/keystore.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```


- The default paths used by cmake, unless ran explicitly from a different directory, overwrites `Makefile`, which is tracked in the repository. This is definitely not an acceptable behavior. Consider renaming the original Makefile to makefile, or even better, moving the cmake files to a different directory (IDE/cmake? ..not the root of the repo!) to avoid this side effect.

- Please improve the step-by-step guide to compile wolfBoot with CMAKE, including the output expected in the intermediate steps

- Please test the cmake build with (at least) the default tatget parameters in tools/config.mk (STM32F4 + Ed25519 and SHA256).

**Comment by lealem47** [comment]
Thanks for the feedback Danielle.
> * running cmake with default parameters leads to a segmentation fault.
>   e.g. with the command line
>
> ```
> -DWOLFBOOT_TARGET=stm32f4 -DWOLFBOOT_PARTITION_SIZE=0x20000 -DWOLFBOOT_SECTOR_SIZE=0x20000 -DWOLFBOOT_PARTITION_BOOT_ADDRESS=0x08020000 -DWOLFBOOT_PARTITION_UPDATE_ADDRESS=0x08040000 -DWOLFBOOT_PARTITION_SWAP_ADDRESS=0x08060000
> ```
> 
> I got:
> 
> ```
>  [ 26%] Generating keystore.c and signing private key
> make[2]: *** [CMakeFiles/keystore.dir/build.make:79: keystore.c] Segmentation fault (core dumped)
> make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/keystore.dir/all] Error 2
> make: *** [Makefile:91: all] Error 2
> ```

This should be fixed now. 

> * The default paths used by cmake, unless ran explicitly from a different directory, overwrites `Makefile`, which is tracked in the repository. This is definitely not an acceptable behavior. Consider renaming the original Makefile to makefile, or even better, moving the cmake files to a different directory (IDE/cmake? ..not the root of the repo!) to avoid this side effect.

I can move the cmake file into something like IDE/cmake but I think this problem is normally addressed by creating a directory `build` and running cmake in that directory with `cmake ..`. That should included that in the cmake instructions.

> * Please improve the step-by-step guide to compile wolfBoot with CMAKE, including the output expected in the intermediate steps

I've added instructions to receive the build options prompt as well as expected output. Anything else you would like to see here?

> * Please test the cmake build with (at least) the default tatget parameters in tools/config.mk (STM32F4 + Ed25519 and SHA256).

Done.

**Comment by lealem47** [comment]
The last commit helps guard for overwriting `Makefile`.

**Review by dgarske — APPROVED** [review]

**Review by dgarske — CHANGES_REQUESTED** [review]
Just noticed some places still using `##WOLFBOOT_ORIGIN##` and `##WOLFBOOT_PARTITION_BOOT_ADDRESS##` after rebase.

**Comment by lealem47** [comment]
> Please document a few more examples of supported platforms with cmake. We have stm32h7, but we support a few others.
> 
> Example `-DWOLFBOOT_TARGET=stm32f4 -DWOLFBOOT_PARTITION_SIZE=0x20000 -DWOLFBOOT_SECTOR_SIZE=0x20000 -DWOLFBOOT_PARTITION_BOOT_ADDRESS=0x08020000 -DWOLFBOOT_PARTITION_UPDATE_ADDRESS=0x08040000 -DWOLFBOOT_PARTITION_SWAP_ADDRESS=0x08060000`

Added example commands for `stm32f4`, `stm32l0`, and `stm32u5`

**Review by dgarske — APPROVED** [review]

**Review by dgarske — APPROVED** [review]

**Pull request merged**
