### PR TITLE
Add support for MIMXRT1042XJM5B

### PR DESCRIPTION
**Pull request by MulattoKid**
This PR adds support for `MIMXRT1042XJM5B`. I've tested this locally on the EVK and a custom PCB, and it works on both.

My approach was:
- search for places where the 1052 was referenced and adding support for the 1042
- run `make` and fix compilation warnings for both `wolfBoot` and the test application

I added local support for patching the test app's ELF file to add the signature to it. Doing so I could flash both `wolfBoot` and the test app through `VSCode`, and was able to get to both binaries `main` entrypoints.

I've not tested that this doesn't break any of the other RT targets.

@danielinux This is the support we discussed during our call. Hopefully this can help getting 1042 support included in `wolfBoot`.

Kind regards,
Daniel

### CODE REVIEW

**Comment by dgarske** [comment]
See ZD 17479

**Comment by MulattoKid** [comment]
One thing I forgot to mention was that in `uart_init` in `hal/imx_rt.c` I had to specifically configure the pins used for debug output like so:
``` C
CLOCK_EnableClock(kCLOCK_Iomuxc);
IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U);
IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U);
IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0x10B0U);
IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0x10B0U);
```
When not doing this, I didn't get any debug output from the bootloader. I did compile with
```
DEBUG_UART?=1
PRINTF_ENABLED?=1
```
in my `.config`. Not sure if I'm missing something?

**Comment by dgarske** [comment]
Hi @MulattoKid , 

Thank you so much for this PR. Your contributor agreement has been accepted and placed on file. 

We've assigned this PR to @bigbrett for review. 

Thanks,
David Garske, wolfSSL

**Review by bigbrett — APPROVED** [review]
Code additions look great, and confirmed no regressions on this branch when building for the RT1052 and RT1054 targets.

**Comment by bigbrett** [comment]
> One thing I forgot to mention was that in `uart_init` in `hal/imx_rt.c` I had to specifically configure the pins used for debug output like so:
> 
> ```c
> CLOCK_EnableClock(kCLOCK_Iomuxc);
> IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0U);
> IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0U);
> IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 0x10B0U);
> IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0x10B0U);
> ```
> 
> When not doing this, I didn't get any debug output from the bootloader. I did compile with
> 
> ```
> DEBUG_UART?=1
> PRINTF_ENABLED?=1
> ```
> 
> in my `.config`. Not sure if I'm missing something?

@MulattoKid Not sure off the top of my head, I will look into this more. It doesn't appear that the hal layer does this pin mux initialization, which could be why printouts don't show up. Regardless, I don't want this to block your PR.

**Review by dgarske — APPROVED** [review]
Thank you @MulattoKid

**Comment by MulattoKid** [comment]
Thanks for the quick responses :)

**Pull request merged**
